version: '3.0'

services:
  api_gateway:
    container_name: api_gateway
    build: 
      context: .
    env_file:
      #- .development.env
      - .production.env
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 8000:8000
    command: npm run start
    restart: always
    networks:
      - bpt-main_default

networks:
  bpt-main_default:
    external: true